export const GET_ALL_GAMES = "GET_ALL"
export const GET_GENRES = "GET_GENRES"
export const SET_GAMES = "SET_GAMES"
export const SEARCH= "SEARCH"
export const FILTER_GAMES = "FILTER_GAMES"
export const SORT_GAMES = "SORT_GAMES"
export const GET_PLATFORMS = "GET_PLATFORMS"
export const CLEAR = "CLEAR"
